### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by knutole** [mapic/shiny-server-pro.docker#1]
### config
- [ ] add nginx proxy server ([guide](https://www.r-bloggers.com/shiny-server-series-part-2-running-shiny-on-multiple-ports/))
- [ ] add SSL using certbot [guide](https://www.r-bloggers.com/shiny-server-series-part-3-adding-ssl-encryption/)
- [ ] add password-less login: email magic link, SMS or TOTP with Auth0 ([guide](https://www.r-bloggers.com/shiny-server-series-part-4-adding-user-authentication-using-auth0/))

### admin
- [ ] databehandler-avtale
- [ ] dokumentasjon

**Comment by knutole** [comment]
## Docker Compose
_Floating Server not part of compose. Will run stand-alone, since it shouldn't be restarted often._

### Containers
- [ ] nginx container, for reverse-proxying: Auth0, public- and private access
- [ ] Shiny Server Pro container. Should be pulled directly from repository.
- [ ] Auth0 nodejs proxy https://github.com/mapic/shiny-auth0.docker
